AWSTemplateFormatVersion: '2010-09-09'
Description: 'S3 Bucket Configuration for Static Assets'

Parameters:
  EnvironmentName:
    Type: String
    Default: dev

  BucketName:
    Type: String
    Description: Name of the S3 bucket

Resources:
  StaticAssetsBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Ref BucketName
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      LifecycleConfiguration:
        Rules:
          - Id: TransitionToIA
            Status: Enabled
            Transitions:
              - StorageClass: STANDARD_IA
                TransitionInDays: 90
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-static-assets

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref StaticAssetsBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowSSLRequestsOnly
            Effect: Deny
            Principal: '*'
            Action: s3:*
            Resource:
              - !Sub ${StaticAssetsBucket.Arn}/*
              - !GetAtt StaticAssetsBucket.Arn
            Condition:
              Bool:
                aws:SecureTransport: false

Outputs:
  BucketName:
    Description: Name of the created S3 bucket
    Value: !Ref StaticAssetsBucket
    Export:
      Name: !Sub ${AWS::StackName}-BucketName

  BucketArn:
    Description: ARN of the created S3 bucket
    Value: !GetAtt StaticAssetsBucket.Arn
    Export:
      Name: !Sub ${AWS::StackName}-BucketArn